/**
 * Petman REST API
 * Petman REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BreederSearchEntry { 
    avatarPreview?: string;
    breed0?: number;
    breed1?: number;
    breed2?: number;
    cityId?: number;
    description?: string;
    id?: number;
    name?: string;
    numPuppies?: number;
    photoPreview?: string;
}
