/**
 * Petman REST API
 * Petman REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Photo } from './photo';


export interface BreederAbout { 
    about: string;
    certificates?: Array<Photo>;
    clubs?: string;
    howItStarted?: string;
    id?: number;
    outstandingInfo?: string;
    photo?: Photo;
}
