/**
 * Petman REST API
 * Petman REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BreederAbout } from './breederAbout';
import { BreederInfo } from './breederInfo';
import { ParentsInfo } from './parentsInfo';
import { PuppiesInfo } from './puppiesInfo';
import { Puppy } from './puppy';


export interface Breeder { 
    about?: BreederAbout;
    createDate?: Date;
    generalInfo?: BreederInfo;
    id?: number;
    name: string;
    parentsInfo?: ParentsInfo;
    phone?: string;
    profileFill?: number;
    puppies?: Array<Puppy>;
    puppiesInfo?: PuppiesInfo;
    puppyDraft?: Puppy;
    questions?: Array<string>;
    status?: Breeder.StatusEnum;
    surname: string;
}
export namespace Breeder {
    export type StatusEnum = 'UNCONFIRMED' | 'ACTIVE' | 'HIDDEN' | 'BLOCKED' | 'DELETED';
    export const StatusEnum = {
        UNCONFIRMED: 'UNCONFIRMED' as StatusEnum,
        ACTIVE: 'ACTIVE' as StatusEnum,
        HIDDEN: 'HIDDEN' as StatusEnum,
        BLOCKED: 'BLOCKED' as StatusEnum,
        DELETED: 'DELETED' as StatusEnum
    };
}
