/**
 * Petman REST API
 * Petman REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PuppyTest } from './puppyTest';


export interface PuppiesInfo { 
    age?: number;
    gifts?: string;
    id?: number;
    insuranceCoverage?: string;
    insuranceTerm: number;
    petmanContract: boolean;
    petmanSet: boolean;
    priceFrom?: number;
    priceTo: number;
    puppyTests: Array<PuppyTest>;
}
