/**
 * Petman REST API
 * Petman REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Parent } from './parent';
import { Photo } from './photo';
import { Breed } from './breed';


export interface Puppy { 
    about: string;
    birthDate: string;
    earmark: string;
    father: Parent;
    gallery?: Array<Photo>;
    gender: Puppy.GenderEnum;
    id?: number;
    mother: Parent;
    nickname: string;
    price: number;
    breed: Breed
}
export namespace Puppy {
    export type GenderEnum = 'MALE' | 'FEMALE';
    export const GenderEnum = {
        MALE: 'MALE' as GenderEnum,
        FEMALE: 'FEMALE' as GenderEnum
    };
}
